{#
    Great-circle distance in km between two latitude/longitude points.

    A macro is SQL generated by Jinja: this one expands inline, wherever it is
    called. DuckDB's spatial extension has an equivalent, but it would have to be
    downloaded at runtime. Spark's analyzer uses the same formula
    (streaming/analyzer/rules.py → haversine_km).
#}
{% macro haversine_km(lat1, lon1, lat2, lon2) -%}
    (2 * 6371 * asin(sqrt(
        pow(sin(radians({{ lat2 }} - {{ lat1 }}) / 2), 2)
        + cos(radians({{ lat1 }})) * cos(radians({{ lat2 }}))
          * pow(sin(radians({{ lon2 }} - {{ lon1 }}) / 2), 2)
    )))
{%- endmacro %}
